name: samesh_wsl_py312
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.12.2=h06a4308_0
  - expat=2.7.4=h7354ed3_0
  - ld_impl_linux-64=2.44=h153f514_2
  - libexpat=2.7.4=h7354ed3_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=15.2.0=h69a1729_7
  - libgcc-ng=15.2.0=h166f726_7
  - libgomp=15.2.0=h4751f2c_7
  - libnsl=2.0.0=h5eee18b_0
  - libstdcxx=15.2.0=h39759b7_7
  - libstdcxx-ng=15.2.0=hc03a8fd_7
  - libuuid=1.41.5=h5eee18b_0
  - libxcb=1.17.0=h9b100fa_0
  - libzlib=1.3.1=hb25bd0a_0
  - ncurses=6.5=h7934f7d_0
  - openssl=3.0.19=h1b28b03_0
  - packaging=25.0=py312h06a4308_1
  - pip=26.0.1=pyhc872135_0
  - pthread-stubs=0.3=h0ce48e5_1
  - python=3.12.12=hd17a9e1_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.10.2=py312h06a4308_0
  - sqlite=3.51.1=he0a8d7e_0
  - tk=8.6.15=h54e0aa7_0
  - wheel=0.46.3=py312h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zlib=1.3.1=hb25bd0a_0
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.13.3
      - aiosignal==1.4.0
      - annotated-doc==0.0.4
      - antlr4-python3-runtime==4.9.3
      - anyio==4.12.1
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.4.0
      - asttokens==3.0.1
      - async-lru==2.1.0
      - attrs==25.4.0
      - babel==2.18.0
      - beautifulsoup4==4.14.3
      - bleach==6.3.0
      - certifi==2026.1.4
      - cffi==2.0.0
      - charset-normalizer==3.4.4
      - click==8.3.1
      - comm==0.2.3
      - contourpy==1.3.3
      - cuda-bindings==12.9.4
      - cuda-pathfinder==1.3.4
      - cycler==0.12.1
      - debugpy==1.8.20
      - decorator==5.2.1
      - defusedxml==0.7.1
      - executing==2.2.1
      - fastjsonschema==2.21.2
      - filelock==3.24.1
      - fonttools==4.61.1
      - fqdn==1.5.1
      - freetype-py==2.5.1
      - frozenlist==1.8.0
      - fsspec==2026.2.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.4.1
      - hydra-core==1.3.2
      - idna==3.11
      - igraph==1.0.0
      - imageio==2.37.2
      - iopath==0.1.10
      - ipykernel==7.2.0
      - ipython==9.10.0
      - ipython-pygments-lexers==1.1.1
      - ipywidgets==8.1.8
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.6
      - joblib==1.5.3
      - json5==0.13.0
      - jsonpointer==3.0.0
      - jsonschema==4.26.0
      - jsonschema-specifications==2025.9.1
      - jupyter==1.1.1
      - jupyter-client==8.8.0
      - jupyter-console==6.6.3
      - jupyter-core==5.9.1
      - jupyter-events==0.12.0
      - jupyter-lsp==2.3.0
      - jupyter-server==2.17.0
      - jupyter-server-terminals==0.5.4
      - jupyterlab==4.5.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.28.0
      - jupyterlab-widgets==3.0.16
      - kiwisolver==1.4.9
      - lark==1.3.1
      - lightning==2.6.1
      - lightning-utilities==0.15.2
      - markdown-it-py==4.0.0
      - markupsafe==3.0.3
      - matplotlib==3.10.8
      - matplotlib-inline==0.2.1
      - mdurl==0.1.2
      - mistune==3.2.0
      - mpmath==1.3.0
      - multidict==6.7.1
      - natsort==8.4.0
      - nbclient==0.10.4
      - nbconvert==7.17.0
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.6.1
      - notebook==7.5.3
      - notebook-shim==0.2.4
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.4.5
      - nvidia-nvtx-cu12==12.1.105
      - omegaconf==2.3.0
      - opencv-python==4.11.0.86
      - pandas==3.0.0
      - pandocfilters==1.5.1
      - parso==0.8.6
      - pexpect==4.9.0
      - pillow==12.1.1
      - platformdirs==4.9.1
      - portalocker==3.2.0
      - prometheus-client==0.24.1
      - prompt-toolkit==3.0.52
      - propcache==0.4.1
      - psutil==7.2.2
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==3.0
      - pyglet==2.1.13
      - pygments==2.19.2
      - pymeshlab==2025.7.post1
      - pyopengl==3.1.7
      - pyparsing==3.3.2
      - pyrender==0.1.45
      - python-dateutil==2.9.0.post0
      - python-json-logger==4.0.0
      - pytorch-lightning==2.6.1
      - pyyaml==6.0.3
      - pyzmq==27.1.0
      - referencing==0.37.0
      - regex==2026.1.15
      - requests==2.32.5
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rfc3987-syntax==1.1.0
      - rich==14.3.2
      - rpds-py==0.30.0
      - safetensors==0.7.0
      - sam-2==1.0
      - scikit-learn==1.8.0
      - scipy==1.17.0
      - send2trash==2.1.0
      - shellingham==1.5.4
      - six==1.17.0
      - soupsieve==2.8.3
      - stack-data==0.6.3
      - sympy==1.14.0
      - terminado==0.18.1
      - texttable==1.7.0
      - threadpoolctl==3.6.0
      - tinycss2==1.4.0
      - tokenizers==0.22.2
      - torch==2.4.1
      - torchaudio==2.4.1
      - torchmetrics==1.8.2
      - torchtyping==0.1.5
      - torchvision==0.19.1
      - tornado==6.5.4
      - tqdm==4.67.3
      - traitlets==5.14.3
      - transformers==5.1.0
      - trimesh==4.11.2
      - triton==3.0.0
      - typeguard==2.13.3
      - typer==0.23.1
      - typer-slim==0.23.1
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - uri-template==1.3.0
      - urllib3==2.6.3
      - wcwidth==0.6.0
      - webcolors==25.10.0
      - webencodings==0.5.1
      - websocket-client==1.9.0
      - widgetsnbextension==4.0.15
      - yarl==1.22.0
prefix: /home/jasmin/miniconda3/envs/samesh_wsl_py312
